### ISSUE TITLE
Stable ABI yet, or mandatory SONAME bump on each release?

### ISSUE THREAD

**Issue by sten0** [Martchus/qtforkawesome#4]
Hi @Martchus!

I've picked up on the Debian packaging effort for qtforkawesome where @hrittich left off, and I'm guessing that the ABI will change [~~between~~] from version to version, and a corresponding soname bump will also occur until the eventual release of 1.0.  Is this truly the case?  Assuming it is, this is totally understandable for early releases, of course, and I don't want to rush you to stabilise, because I feel like it's too early for that :-)  Eventually I'll ask for practical reasons, but that time is far away!

Regards,
Nicholas

**Comment by Martchus** [comment]
Yes, an ABI break will always be an soname bump. Currently, the soname includes the full version. Maybe I'll reduce the soname to major.minor or just major version at some point. I haven't planned that yet. If the library is only used by Syncthing Tray there's actually no point in preserving the ABI (and even API) as a new release of qtforkawesome will be done at the same time as a new release of syncthingtray so you'd just rebuild both projects at the same time anyways.

**Comment by sten0** [comment]
Thank you for the reply, and sorry for the delay in mine.

Within a Debian context there is a concrete, pragmatic reason for ABI stability:  Each ABI requires another trip through the [NEW queue](https://ftp-master.debian.org/new.html), which can sometimes take months.  Ie this will currently occur for every Qt Forkawesome (and other Syncthing Tray dependencies) release.

Once again, I'll leave it to you to decide when is an appropriate time to do so :)  If you'd like, I can also share when this issue emerges so you can determine if it's significant enough to be worth prioritising.

**Comment by Martchus** [comment]
I'm closing the issue because the question was answered.
