### ISSUE TITLE
question about enhancing the description

### ISSUE THREAD

**Issue by sten0** [Martchus/qtforkawesome#5]
In Debian, the word "bundling" has a specific definition with negative connotations.  So far, I can see that qtforkawesome:

1. Allows Fork Awesome font icons to be used as objects rather than…I'm not sure what to write as the alternative.  Are these convenience classes and/or syntactic sugar? 
2. Provides an icon engine plugin
3. Provides QQuickImageProvider for use in QQmlEngine

So rather than "Library that bundles ForkAwesome for use within Qt applications", I would like to write something comparably short  that presents Qt Fork Awesome in a better light within a Debian context.  Something more like "Library that makes ForkAwesome assets addressable using native Qt methods", but I'm pretty sure "addressable" is the wrong word ;-)

Thanks in advance!

**Comment by Martchus** [comment]
I'm quite reluctant to rephrase this just for the sake of avoiding a burned word. I suppose you could replace "bundles" with "embeds" or "provides". The library basically does everything needed to use ForkAwesome in Qt apps conveniently:

1. Provide a C++ `enum` with all the icon definitions. This code is generated from ForkAwesome's definitions. So their YAML file is basically converted to a C++ header file, replicating the information.
2. Provide the font file itself (which must be in accordance to 1.) as resource built into the library that is accessible by Qt's resource system.
3. Provide some helpers to conveniently render font glyphs where Qt normally expects icons. This part is actually independent from ForkAwesome and could be re-used for any kind of icon-font.

Going into so much detail likely makes no sense for a package description. Maybe you can just write "Library to use ForkAwesome within Qt applications".

**Comment by sten0** [comment]
It's a bit more than just a burned word...  Debian packages have both a short and a long description; The short one is easy; Thanks for help with the long one!  It's done now and is also GPL-2+ so you're welcome to copy it. :)
